---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task

inputs:
- name: s3c-repo
- name: s3c-binary

outputs:
- name: s3c-image

run:
  path: s3c-repo/ci/tasks/build.sh
