---
platform: linux

inputs:
- name: s3c-repo
- name: s3c-image

params:
  IMAGE:
  # - path to the image file to sign

  COSIGN_KEY:
  # - base64 encoded private key to sign the image with

  COSIGN_PASSWOWRD:
  # - password to the above key

run:
  path: s3c-repo/ci/tasks/cosign.sh
