resources:
- name: s3c-example-ci-image
  type: registry-image
  source:
    repository: harbor.plat-svcs.pez.vmware.com/library/s3c-example-ci
    username: ((registry-username))
    password: ((registry-password))

- name: s3c-repo
  type: git
  source:
    private_key: ((concourse_github_deploy_key))
    uri: git@github.com:sneal/s3c-example.git

jobs:
- name: build
  plan:
  - in_parallel:
    - get: s3c-example-ci-image
    - get: s3c-repo
  - task: compile
    image: s3c-example-ci-image
    file: s3c-repo/ci/tasks/compile.yml
  - task: build-image
    privileged: true
    file: s3c-repo/ci/tasks/build.yml
    params:
      DOCKERFILE: s3c-repo/Dockerfile
